name: Build and Push NuGet Package (.NET Framework 4.8)

on:
  push:
    tags:
      - 'v*'  # Triggers on version tags like v1.0.0

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1

    - name: Restore packages
      run: nuget restore TestAutomationService.sln

    - name: Build project
      run: msbuild TestAutomationService/TestAutomationService.csproj /p:Configuration=Release

    - name: Pack NuGet package
      run: nuget pack TestAutomationService.nuspec -OutputDirectory ./nupkg
